### ISSUE TITLE
Extra whitespace after compound glyphs

### ISSUE THREAD

**Issue by skalyan91** [davidar/linja-pona#4]
On Safari, and in TextEdit, compound glyphs seem to take up double the horizontal space of a single glyph. For example, this is what https://davidar.github.io/tp/sona-nasa-pi-jan-ansan looks like for me in Safari:
![image](https://user-images.githubusercontent.com/2990272/62002271-f69e3780-b143-11e9-919b-e10a9ab04ae1.png)
This problem does not arise in Chrome.

**Comment by davidar** [comment]
Hm, Chrome has a similar issue when using `-` (hyphen) to combine glyphs, but works fine when using `+` (plus) instead. I guess Safari has an issue with both? Do you see the same issue with the compound glyphs in v3 of linja pona?

**Comment by skalyan91** [comment]
I don’t have any issue with hyphens in Chrome (on Mac); here is what I get if I enter `mi tawa tomo-sona kepeken tomo-tawa.` in https://davidar.github.io/linja-pona/:

![image](https://user-images.githubusercontent.com/2990272/62004552-0fb9df00-b16a-11e9-9918-6f9785666737.png)

Safari (and TextEdit) have an issue with both hyphens and pluses. I haven’t tried linja pona v3 in the browser (do you know of a website that uses it as a webfont?), but it works fine in TextEdit.

**Comment by davidar** [comment]
Ah, Inkscape (on Linux) has the same issue:

![Screenshot_20190730_172531](https://user-images.githubusercontent.com/24291/62109143-08700e00-b2ef-11e9-9762-e7561775cf7a.png)

I have an idea of something that might fix it, but I'll need to test it first.

**Comment by davidar** [comment]
@skalyan91 can you check if this fixes the issue for you (in TextEdit, at least)?

:paperclip: [linja-pona.zip](https://github.com/davidar/linja-pona/files/3446311/linja-pona.zip) (eed4bb2)

**Comment by skalyan91** [comment]
@davidar It works perfectly! Thank you!!

**Comment by skalyan91** [comment]
@davidar When you have a chance, could you please update the repo? I would like to be able to view your website with the newly-working font, and use the webfont myself. Thanks.

**Comment by davidar** [comment]
Done, hopefully the website will work in Safari now :)

**Comment by skalyan91** [comment]
Thanks, it does!
