### ISSUE TITLE
smaller than older versions of the font?

### ISSUE THREAD

**Issue by increpare** [davidar/linja-pona#7]
In both mac Font Book, and in Apple Numbers, the two versions of the font render at different sizes.  Is this intentional?

<img width="324" alt="Bildschirmfoto 2019-09-22 um 02 13 13" src="https://user-images.githubusercontent.com/465632/65380586-9dcfc300-dcde-11e9-88f5-9944d71b807a.png">
(left: yours, right: @janSame's ; both rendered at 10pt)

**Comment by davidar** [comment]
Yeah, the font previously overflowed the line-height, so fixing that (in a way that didn't require users to manually change the line-height) required reducing the size.
